{% set name = "daphne" %}
{% set version = "2.3.0" %}
{% set url = "https://github.com/django/daphne" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name|lower|first }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 2329b7a74b5559f7ea012879c10ba945c3a53df7d8d2b5932a904e3b4c9abcc2

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - twisted
    - autobahn
    - asgiref

test:
  imports:
    - daphne
    - daphne.cli

about:
  home: {{ url }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Django ASGI (HTTP/WebSocket) server"
  description: |
    Daphne is a HTTP, HTTP2 and WebSocket protocol server
    for ASGI and ASGI-HTTP, developed to power Django Channels.
    It supports automatic negotiation of protocols; there's no
    need for URL prefixing to determine WebSocket endpoints
    versus HTTP endpoints.
  doc_url: {{ url }}
  dev_url: {{ url }}

extra:
  recipe-maintainers:
    - sdc50